### ISSUE TITLE
Enable compilation by using FPC 3.2.0 embedded-i386

### ISSUE THREAD

**Issue by MatiasVara** [torokernel/ToroOS#1]
This issue aims at compiling ToroOS 1.1.3 by using FPC-3.2.0 for embedded-i386.

**Comment by MatiasVara** [comment]
This issue should be split into the following tasks:
- [x] Document how to build
- [x] Document how to try
- [ ] Initialize KERNEL stack
- [x] Remove multibot.pas
- [x] Remove head.s
- [x] Move asmb.pas, gdt.pas and cpu.pas to arch.pas and ioport.h too.
- [x] Rename "memoria" to "memory"
- [x] Remove cpu unit
- [x] Remove fpclib
- [x] Move mm.pas and paging.pas into memory.pas
- [x] Move Int to Arch
- [x] Work on Exceptions. Fix workaround.
- [x] Move irq handlers to process
- [x] GdtLock and Memory lock must be implement in process.pas
- [x] To init scheduler in process just when kernel does it
- [x] Compile process.pas
- [x] Add Filesystem to compile process.pas. I am adding all the filesystem into filesystem.pas unit.
- [x] Put wait_queue in arch.pas
- [x] Add to process.pas
- [x] Create Init task as a user process
- [x] Fix FarJump
- [x] Add packed to packed structured
- [x] Fix BitReset and BitSet
- [x] Port syscalls (See #2 and #3)
- [x] Port Filesystem (see #3). For the moment, I added the minimum to make #3.
- [x] Add dma unit (see #3)
- [x] Add floppy unit (see #3)
- [x] Add fatfs (see #3)
- [x] Add exec() syscall.
- [x] Add waitpid syscall().
- [x] Add support for elf32 for exec (see #5)
- [x] Change directory structure: src, tools, rtl (see #4)
- [x] Build an RTL for fpc for Toro (see #6)
- [x] To port ls (see #9)
- [x] To port sh (see #8)
- [x] Create docker to ease compilation (#10)

Next iteration:
- [ ] Reimplement mm_total_fisica()
- [ ] Document how Makefiles are created
- [ ] Rewrite printk.pas
- [ ] Add ide-disk driver (see #7)
- [ ] Handle better the ignored exceptions
- [ ] Add a unit to handle queues and hashes
- [ ] Refactor arch/arch.pas
- [ ] Refactor memory/memory.pas
- [ ] Replace macros.inc with something better
- [ ] Remove coff structures in fs
- [ ] Remove public functions
- [ ] Add ext2 driver
- [x] Create lazarus project
- [ ] Add serial driver
- [ ] Add kernel command line parameters
- [x] Rewrite sh (See #21 ) (refactor into `getline(&buff)`, `get_cmd_and_args(&cmd, &args)`, `do_cmd(cmd, args)`, `builtin_cmds(cmd, args)` and `exec_cmd()`)
- [x] Add ioresult and errno
- [ ] Port cat
- [x] Rewrite the tty driver (See #23 and #24)
- [x] Rewrite ls (See #26)
- [x] Add app parameters (See #27 and #28)
- [ ] Rewrite echo (See #29 )
- [ ] Use an empty image and fix the issues with new files
- [x] read() and readln are always reading 256 bytes
- [x] Add ReadKey()

Next Next iteration:
- [ ] Create first release and add it a CI
- [ ] To use the same syscall and ABI that Linux. Try with a simple C program using the Write Syscall for Linux
